[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/_stcore/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
# Railway will automatically set PORT
# Add your environment variables here or in Railway dashboard
PYTHONPATH = "/app"
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"

# OAuth2 Deriv Configuration
# Note: Set these in Railway dashboard for security
# DERIV_APP_ID = "your_app_id"
# DERIV_CLIENT_SECRET = "your_client_secret"
# DERIV_API_TOKEN = "your_api_token"

# Railway Environment Detection
RAILWAY = "true"

# Streamlit specific configurations
STREAMLIT_SERVER_PORT = "$PORT"
STREAMLIT_SERVER_ADDRESS = "0.0.0.0"
STREAMLIT_SERVER_HEADLESS = "true"
STREAMLIT_BROWSER_GATHER_USAGE_STATS = "false"
STREAMLIT_SERVER_ENABLE_CORS = "false"
STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION = "false"
STREAMLIT_GLOBAL_DEVELOPMENT_MODE = "false"
STREAMLIT_CLIENT_CACHING = "true"
STREAMLIT_RUNNER_INSTALL_TRACER = "false"

[experimental]
# Enable Railway's new build system
nixpacks = false